# Generated by Django 6.0.6 on 2026-07-08 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('push', 'Push'), ('pull_request', 'Pull Request'), ('issues', 'Issue')], max_length=50)),
                ('action_type', models.CharField(choices=[('notification', 'Create Notification'), ('log', 'Save Log')], max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_bot.repository')),
            ],
        ),
    ]
